const permission = {
  PERMISSIONS: {
    ACCESS_BACKGROUND_LOCATION: 'android.permission.ACCESS_BACKGROUND_LOCATION',
    ACCESS_COARSE_LOCATION: 'android.permission.ACCESS_COARSE_LOCATION',
    ACCESS_FINE_LOCATION: 'android.permission.ACCESS_FINE_LOCATION',
    ADD_VOICEMAIL: 'com.android.voicemail.permission.ADD_VOICEMAIL',
    BLUETOOTH_ADVERTISE: 'android.permission.BLUETOOTH_ADVERTISE',
    BLUETOOTH_CONNECT: 'android.permission.BLUETOOTH_CONNECT',
    BLUETOOTH_SCAN: 'android.permission.BLUETOOTH_SCAN',
    BODY_SENSORS: 'android.permission.BODY_SENSORS',
    CALL_PHONE: 'android.permission.CALL_PHONE',
    CAMERA: 'android.permission.CAMERA',
    GET_ACCOUNTS: 'android.permission.GET_ACCOUNTS',
    PROCESS_OUTGOING_CALLS: 'android.permission.PROCESS_OUTGOING_CALLS',
    READ_CALENDAR: 'android.permission.READ_CALENDAR',
    READ_CALL_LOG: 'android.permission.READ_CALL_LOG',
    READ_CONTACTS: 'android.permission.READ_CONTACTS',
    READ_EXTERNAL_STORAGE: 'android.permission.READ_EXTERNAL_STORAGE',
    READ_PHONE_STATE: 'android.permission.READ_PHONE_STATE',
    READ_SMS: 'android.permission.READ_SMS',
    RECEIVE_MMS: 'android.permission.RECEIVE_MMS',
    RECEIVE_SMS: 'android.permission.RECEIVE_SMS',
    RECEIVE_WAP_PUSH: 'android.permission.RECEIVE_WAP_PUSH',
    RECORD_AUDIO: 'android.permission.RECORD_AUDIO',
    SEND_SMS: 'android.permission.SEND_SMS',
    USE_SIP: 'android.permission.USE_SIP',
    WRITE_CALENDAR: 'android.permission.WRITE_CALENDAR',
    WRITE_CALL_LOG: 'android.permission.WRITE_CALL_LOG',
    WRITE_CONTACTS: 'android.permission.WRITE_CONTACTS',
    WRITE_EXTERNAL_STORAGE: 'android.permission.WRITE_EXTERNAL_STORAGE',
  },
  RESULTS: {
    DENIED: 'denied',
    GRANTED: 'granted',
    NEVER_ASK_AGAIN: 'never_ask_again',
  },
};
const locationResponseData = {
  plus_code: {
    compound_code: '588C+JW2 Jagadhri, Haryana, India',
    global_code: '8J2V588C+JW2',
  },
  results: [
    {
      address_components: [Array],
      formatted_address:
        '588C+9V4, Green Vihar Colony, जगाधरी, हरियाणा 135003, India',
      geometry: [Object],
      place_id: 'ChIJh9uty5n7DjkRndlE2JbI3wA',
      types: [Array],
    },
    {
      address_components: [Array],
      formatted_address:
        '588C+9V4, Green Vihar Colony, जगाधरी, हरियाणा 135003, India',
      geometry: [Object],
      place_id: 'ChIJ3dorDZH7DjkR3Sk1sFkqefM',
      types: [Array],
    },
    {
      address_components: [Array],
      formatted_address: '588C+JW Jagadhri, Haryana, India',
      geometry: [Object],
      place_id: 'GhIJVYzzN6EqPkARByP2CaBUU0A',
      plus_code: [Object],
      types: [Array],
    },
    {
      address_components: [Array],
      formatted_address:
        'Unnamed Road, Ganga Nagar Colony, Jagadhri, Haryana 135003, India',
      geometry: [Object],
      place_id: 'ChIJe8Ooupn7DjkRIplYKHFgTac',
      types: [Array],
    },
    {
      address_components: [Array],
      formatted_address: 'Green Vihar Colony, जगाधरी, हरियाणा 135003, India',
      geometry: [Object],
      place_id: 'ChIJJY-Qmpn7DjkRXQWNJmiAS_w',
      types: [Array],
    },
    {
      address_components: [Array],
      formatted_address: 'Jagadhri, Haryana, India',
      geometry: [Object],
      place_id: 'ChIJ69DAPe77DjkR0kfnMwLFBfE',
      types: [Array],
    },
    {
      address_components: [Array],
      formatted_address: 'Haryana 135003, India',
      geometry: [Object],
      place_id: 'ChIJQQf95XzkDjkRnH5el0KgR2Q',
      types: [Array],
    },
    {
      address_components: [Array],
      formatted_address: 'Yamuna Nagar, Haryana, India',
      geometry: [Object],
      place_id: 'ChIJq8E8eCv6DjkRzV3Inme1jNI',
      types: [Array],
    },
    {
      address_components: [Array],
      formatted_address: 'Haryana, India',
      geometry: [Object],
      place_id: 'ChIJC0BwhguwDTkRQ8GmqrSqLnM',
      types: [Array],
    },
    {
      address_components: [Array],
      formatted_address: 'India',
      geometry: [Object],
      place_id: 'ChIJkbeSa_BfYzARphNChaFPjNc',
      types: [Array],
    },
  ],
  status: 'OK',
};
